### ISSUE TITLE
Failed to run phpmyadmin

### ISSUE THREAD

**Issue by TiGReX423** [ddev/ddev-phpmyadmin#11]
I want to create small project for task.
Windows 10.
1)Start docker desktop.
2)Open windows cmd
In cmd:
2.1)cd C:\web2
2.2)ddev start
(I already configured ddev to this folder)
2.3)ddev get ddev/ddev-phpmyadmin
(Since I haven't got any other WSL before, it was used Docker desktop as default and it didn't allow to install phpmyadmin)
(Solution was to install manually Ubuntu-22.04 and changing wsl to new Ubuntu-22.04)
Installation successful.
2.4)ddev restart
After restart, in cmd.
2.5)ddev phpmyadmin
And I receive this message:

/bin/bash: C:web2.ddevcommandshostphpmyadmin: No such file or directory
Failed to run phpmyadmin ; error=exit status 127

Cant figure out what should I do.
Posting here because it seems that here is lack of information in installation guide.

**Comment by rfay** [comment]
Are you using git bash? You probably have to. It's recommended for people who work on traditional Windows. It's also possible that the `bash` in your $PATH isn't git-bash.

**Comment by TiGReX423** [comment]
I installed Git from official webpage. Ran it as "windows cmd" like terminal. Now everything works. Thanks for the help!
(problem was in path "styling", '/c/Users/username/' is Unix-style and 'C:\Users\username\' is windows style which I was using before)

**Comment by rfay** [comment]
Yay!
