### ISSUE TITLE
`ddev phpmyadmin` doesn't work in Gitpod

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev-phpmyadmin#15]
From Discord: https://discord.com/channels/664580571770388500/1260544940216291339

`ddev phpmyadmin` doesn't open the correct port.

**Comment by stasadev** [comment]
And `ddev phpmyadmin` will not work until this issue is resolved:

- https://github.com/ddev/ddev/issues/6389

**Comment by stasadev** [comment]
Wow, the thing I suggested is already here:

- https://github.com/ddev/ddev-phpmyadmin/pull/4

But it doesn't work.

I see an empty file `.ddev/docker-compose.phpmyadmin-norouter.yaml` in Gitpod:

```yaml
#ddev-generated
# If omit_containers[ddev-router] then this file will be replaced
# with another with a `ports` statement to directly expose port 80 to 8036
services: {}
```

**Comment by rfay** [comment]
This approach seems to work. It didn't work right in the preview panel, but it works with the port set to public.

**Comment by stasadev** [comment]
Yes, it works, but not yet with ddev-gitpod-launcher:

- https://github.com/ddev/ddev-gitpod-launcher/pull/45

And `ddev phpmyadmin` will not open the correct URL until this PR is merged:

- https://github.com/ddev/ddev/pull/6391

**Comment by rfay** [comment]
I was testing it with 
* https://github.com/ddev/ddev/pull/6391

**Comment by stasadev** [comment]
I did the same test, and `ddev phpmyadmin` was opened on the port `8037`, but `.ddev/docker-compose.phpmyadmin-norouter.yaml` points to `8036`, so we need to change the exposed port here to match it.

> It didn't work right in the preview panel

And add this to README.md
