### ISSUE TITLE
phpMyAdmin container is broken after stopping/starting a workspace in Gitpod

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev-phpmyadmin#17]
From https://discord.com/channels/664580571770388500/1260544940216291339

```
$ ddev start
...
Failed to start d10simple: container(s) failed to become healthy before their configured timeout or in 120 seconds. This might be a problem with the healthcheck and not a functional problem. (ddev-d10simple-phpmyadmin container exited, more info with [
        ddev logs -s phpmyadmin
        docker logs ddev-d10simple-phpmyadmin
        docker inspect --format "{{ json .State.Health }}" ddev-d10simple-phpmyadmin | docker run -i --rm ddev/ddev-utilities jq -r
]) 
```

```
$ ddev logs -s phpmyadmin
...
(13)Permission denied: AH00091: apache2: could not open error log file /var/log/apache2/error.log.
AH00015: Unable to open logs
```

---

To reproduce:

1. Click Open in Gitpod https://ddev.github.io/ddev-gitpod-launcher/
2. Wait for the website to be ready.
3. `ddev get ddev/ddev-phpmyadmin && ddev restart`
4. Stop the workspace here https://gitpod.io/workspaces
5. Start it again, run `ddev start` and see the error for the `phpmyadmin` container.

---

The current image is `5.2.1`.

A workaround is to use a year-old image in `.ddev/docker-compose.phpmyadmin.yaml`:
Don't forget to remove `#ddev-generated` from this file.

```yaml
services:
  phpmyadmin:
    image: phpmyadmin:5.2.0
```

**Comment by rfay** [comment]
I do remember a problem like this in an older phpmyadmin image. It's possible that we shouldn't be using phpmyadmin:5 and instead use a specific version.
