### ISSUE TITLE
No default port is bound, so hard to use on gitpod or codespaces

### ISSUE THREAD

**Issue by RCheesley** [ddev/ddev-phpmyadmin#3]
Hi folks!

When we tried to upgrade to 1.22.0 in [this PR](https://github.com/mautic/mautic/pull/12578) we came up against an issue whereby the PHPMyAdmin port was not getting correctly kicked off in Gitpod, so it was not accessible to users for testing.

It might well be a problem that other Gitpod / Codespace users come across, and can be worked around with the docker-compose.gitpod.yml using 

```
services:
  phpmyadmin:
    ports:
    - "8036:80"
```

in case others come across this from search (thanks @rfay for the suggestion!) but it might be helpful to declare the ports explicitly in the plugin?

**Comment by rfay** [comment]
I think this should be pretty easy to deal with. What we can do is 

if the router is not enabled (Detect maybe with `{{ .DdevGlobalConfig.omit_containers}}` )
  * Add a docker-compose.phpmyadmin-norouter.yaml with the contents above
  * Add to `removal_actions` the deletion of that file (see https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#sections-and-features-of-ddev-get-add-on-installyaml)

That should do it. PR is welcome.

**Comment by rfay** [comment]
Please test 
* https://github.com/ddev/ddev-phpmyadmin/pull/4

Testing instructions are there. I think it should sort this out, seems to work OK for me on gitpod.

**Comment by rfay** [comment]
This is released, please see how it goes for you.
